language: generic

dist: xenial

services:
  - docker

env:    
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"
    - ROS_DISTRO="melodic"
    - ROS_DISTRO="melodic"
      AFTER_SCRIPT="sh ./coverage.sh"

install:
  - git clone --quiet --depth 1 https://github.com/imcatta/industrial_ci .ci

script:
  - .ci/travis.sh
