language: generic

dist: xenial

services:
  - docker

env:
  global:
    - AFTER_SCRIPT='pip install --user codecov nose &&
      cd /tmp &&
      nosetests --cover-package=mapek_framework --with-coverage $TARGET_REPO_PATH/mapek_framework/src &&
      codecov'
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"
    - ROS_DISTRO="melodic"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci

script:
  - .ci/travis.sh
