language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="indigo"

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci
script:
  - .ci/travis.sh
