language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"
    - ROS_DISTRO="melodic"    

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci
  - pip install codecov nose
script:
  - .ci/travis.sh
after_script:
  - cd mapek_framework/src && nosetests --cover-package=mapek_framework --with-coverage && codecov

