language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"
    - ROS_DISTRO="melodic"    

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci
script:
  - .ci/travis.sh
